-- MySQL Script generated by MySQL Workbench
-- Tue Apr  5 13:21:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerId` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Phone` INT NOT NULL,
  PRIMARY KEY (`CustomerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_has_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer_has_Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer_has_Products` (
  `Customer_CustomerId` INT NOT NULL,
  `Products_ProductNumber` INT NOT NULL,
  `Invoice_InvoiceId` INT NOT NULL,
  `Invoice_Sales_Sales ID` INT NOT NULL,
  PRIMARY KEY (`Customer_CustomerId`, `Products_ProductNumber`),
  CONSTRAINT `fk_Customer_has_Products_Customer1`
    FOREIGN KEY (`Customer_CustomerId`)
    REFERENCES `mydb`.`Customer` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Products_Products1`
    FOREIGN KEY (`Products_ProductNumber`)
    REFERENCES `mydb`.`Products` (`ProductNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Products_Invoice1`
    FOREIGN KEY (`Invoice_InvoiceId` , `Invoice_Sales_Sales ID`)
    REFERENCES `mydb`.`Invoice` (`InvoiceId` , `Sales_Sales ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customer_has_Products_Products1_idx` ON `mydb`.`Customer_has_Products` (`Products_ProductNumber` ASC) VISIBLE;

CREATE INDEX `fk_Customer_has_Products_Customer1_idx` ON `mydb`.`Customer_has_Products` (`Customer_CustomerId` ASC) VISIBLE;

CREATE INDEX `fk_Customer_has_Products_Invoice1_idx` ON `mydb`.`Customer_has_Products` (`Invoice_InvoiceId` ASC, `Invoice_Sales_Sales ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `InvoiceId` INT NOT NULL,
  `InvoiceNumber` VARCHAR(45) NOT NULL,
  `InvoiceDate` DATETIME NOT NULL,
  `Sales_Sales ID` INT NOT NULL,
  PRIMARY KEY (`InvoiceId`, `Sales_Sales ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `InvoiceNumber_UNIQUE` ON `mydb`.`Invoice` (`InvoiceNumber` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `ProductNumber` INT NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProductNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products_has_Supplier Table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products_has_Supplier Table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products_has_Supplier Table` (
  `Products_ProductNumber` INT NOT NULL,
  `Supplier Table_Supplier ID` INT NOT NULL,
  PRIMARY KEY (`Products_ProductNumber`, `Supplier Table_Supplier ID`),
  CONSTRAINT `fk_Products_has_Supplier Table_Products`
    FOREIGN KEY (`Products_ProductNumber`)
    REFERENCES `mydb`.`Products` (`ProductNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Supplier Table_Supplier Table1`
    FOREIGN KEY (`Supplier Table_Supplier ID`)
    REFERENCES `mydb`.`Supplier Table` (`Supplier ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Products_has_Supplier Table_Supplier Table1_idx` ON `mydb`.`Products_has_Supplier Table` (`Supplier Table_Supplier ID` ASC) VISIBLE;

CREATE INDEX `fk_Products_has_Supplier Table_Products_idx` ON `mydb`.`Products_has_Supplier Table` (`Products_ProductNumber` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier Table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supplier Table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supplier Table` (
  `Supplier ID` INT NOT NULL,
  `SupplierName` VARCHAR(45) NOT NULL,
  `SupplierContact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Supplier ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
